# image: registry.cn-shanghai.aliyuncs.com/choerodon-tools/cibase:0.9.1
image: registry.elitescloud.com/library/cibase:0.0.2

stages:
  - node-build
  - chart-build

variables:
  GIT_SUBMODULE_STRATEGY: recursive

node-build:
  when: manual
  stage: node-build
  script:
    - export CI_COMMIT_TAG="${CI_COMMIT_TAG}-${CI_PIPELINE_ID}"
    - echo ${CI_COMMIT_TAG}
    - git config --global url."https://".insteadOf git://
    - npm i --registry https://verdaccio.elitescloud.com --sass-binary-site=http://npm.taobao.org/mirrors/node-sass
    - yarn config set registry https://verdaccio.elitescloud.com
    - yarn config set sass_binary_site http://npm.taobao.org/mirrors/node-sass -g
    - yarn install
    - CI=false yarn build
    - mv build docker/
    - ls docker/build
    - docker build --pull -f docker/Dockerfile -t ${DOCKER_REGISTRY}/${GROUP_NAME}/${PROJECT_NAME}:${CI_COMMIT_TAG} docker
    - docker push ${DOCKER_REGISTRY}/${GROUP_NAME}/${PROJECT_NAME}:${CI_COMMIT_TAG}


  except:
      - tags

chart-build:
  when: manual
  stage: chart-build
  script:
    - export CI_COMMIT_TAG="${CI_COMMIT_TAG}-${CI_PIPELINE_ID}"
    - echo ${CI_COMMIT_TAG}
    - chart_build
  except:
      - tags

node-build-tag:
  stage: node-build
  script:
    - export CI_COMMIT_TAG="${CI_COMMIT_TAG}"
    - echo ${CI_COMMIT_TAG}
    - npm i --registry https://nexus.gobuildrun.com/repository/br_npm/ --sass-binary-site=http://npm.taobao.org/mirrors/node-sass
    - chmod -R 777 node_modules
    - npm run dist
    - cp -r src/main/resources/lib docker/lib
    - chmod a+x docker/lib/dist/env.sh
    - docker build --pull -f docker/Dockerfile -t ${DOCKER_REGISTRY}/${GROUP_NAME}/${PROJECT_NAME}:${CI_COMMIT_TAG} docker
    - docker push ${DOCKER_REGISTRY}/${GROUP_NAME}/${PROJECT_NAME}:${CI_COMMIT_TAG}
    # 构建镜像
    #- build_multi_platform_image docker docker/Dockerfile
  only:
      - tags

chart-build-tag:
  stage: chart-build
  script:
    - export CI_COMMIT_TAG="${CI_COMMIT_TAG}"
    - echo ${CI_COMMIT_TAG}
    - chart_build
  only:
      - tags



.auto_devops: &auto_devops |
  http_status_code=`curl -o .auto_devops.sh -s -m 10 --connect-timeout 10 -w %{http_code} "${CHOERODON_URL}/devops/ci?token=${Token}&type=front"`
  if [ "$http_status_code" != "200" ]; then
    cat .auto_devops.sh
    exit 1
  fi
  source .auto_devops.sh

before_script:
  - *auto_devops
